// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muallimi.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Muallimi.Infrastructure.Migrations
{
    [DbContext(typeof(MuallimiDbContext))]
    partial class MuallimiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muallimi.Domain.Content.AutoValidationResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<string>("Accessibility")
                        .HasColumnType("jsonb")
                        .HasColumnName("accessibility");

                    b.Property<string>("Alignment")
                        .HasColumnType("jsonb")
                        .HasColumnName("alignment");

                    b.Property<string>("ArabicQuality")
                        .HasColumnType("jsonb")
                        .HasColumnName("arabic_quality");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("Checks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checks");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("GroundingEvidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("grounding_evidence");

                    b.Property<string>("NarrationSync")
                        .HasColumnType("jsonb")
                        .HasColumnName("narration_sync");

                    b.Property<string>("Rendering")
                        .HasColumnType("jsonb")
                        .HasColumnName("rendering");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("ResultId");

                    b.ToTable("auto_validation_results", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Content.FormatDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("LlmRefinement")
                        .HasColumnType("text")
                        .HasColumnName("llm_refinement");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overridden_at");

                    b.Property<string>("OverriddenBy")
                        .HasColumnType("text")
                        .HasColumnName("overridden_by");

                    b.Property<string>("RuleTriggered")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_triggered");

                    b.Property<string>("SelectedFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_format");

                    b.HasKey("DecisionId");

                    b.ToTable("format_decisions", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Content.GeneratedAsset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<string>("Cost")
                        .HasColumnType("jsonb")
                        .HasColumnName("cost");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime>("ProducedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("produced_at");

                    b.Property<string>("ProducedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("produced_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("VisualFormat")
                        .HasColumnType("text")
                        .HasColumnName("visual_format");

                    b.HasKey("AssetId");

                    b.ToTable("generated_assets", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Content.GenerationJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CostSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("cost_summary");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("text")
                        .HasColumnName("error_reason");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<string>("Stages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stages");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("JobId");

                    b.ToTable("generation_jobs", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Content.IngestionJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("text")
                        .HasColumnName("error_reason");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Stages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stages");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("JobId");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Coverage.CoverageStatus", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("AssetType")
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<long?>("QueueAge")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_age");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("LessonId", "AssetType");

                    b.ToTable("coverage_statuses", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.ChangeLogEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("EntryId");

                    b.ToTable("change_log_entries", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.ContentChunk", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model_version");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MathBlocks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("math_blocks");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("OverlapWithPrevious")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_with_previous");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceRefs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_refs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("ChunkId");

                    b.HasIndex("LessonId");

                    b.ToTable("content_chunks", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.CurriculumSource", b =>
                {
                    b.Property<Guid>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_year");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("CurriculumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curriculum_type");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_format");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TutorLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_language");

                    b.Property<string>("UploadActor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upload_actor");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("SourceId");

                    b.ToTable("curriculum_sources", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.CurriculumStructure", b =>
                {
                    b.Property<Guid>("StructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("structure_id");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nodes");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("StructureId");

                    b.HasIndex("SourceId");

                    b.ToTable("curriculum_structures", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("CurriculumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curriculum_type");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("LastChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("last_change_reason");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("structure_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TutorLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_language");

                    b.HasKey("LessonId");

                    b.HasIndex("StructureId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.QaCacheEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CurriculumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curriculum_type");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<Vector>("QuestionEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("question_embedding");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("SourceChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_chunk_ids");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("TutorLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_language");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_status");

                    b.HasKey("EntryId");

                    b.ToTable("qa_cache_entries", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Publication.PublishedAsset", b =>
                {
                    b.Property<Guid>("PublishedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("published_id");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedByAdmin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approved_by_admin");

                    b.Property<string>("ApprovedByExpert")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approved_by_expert");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("RuntimeUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("runtime_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("VisualFormat")
                        .HasColumnType("text")
                        .HasColumnName("visual_format");

                    b.HasKey("PublishedId");

                    b.ToTable("published_assets", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Review.ReviewAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("AssignmentId");

                    b.ToTable("review_assignments", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Review.ReviewDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("FixInstruction")
                        .HasColumnType("text")
                        .HasColumnName("fix_instruction");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("DecisionId");

                    b.ToTable("review_decisions", (string)null);
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.ContentChunk", b =>
                {
                    b.HasOne("Muallimi.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.CurriculumStructure", b =>
                {
                    b.HasOne("Muallimi.Domain.Curriculum.CurriculumSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Muallimi.Domain.Curriculum.Lesson", b =>
                {
                    b.HasOne("Muallimi.Domain.Curriculum.CurriculumStructure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Structure");
                });
#pragma warning restore 612, 618
        }
    }
}
